2021-08-17 08:15:22.851[ WARNING ]
app.licenseware.app_builder.app_builder:init_app:117
No reports provided

2021-08-17 08:16:54.539[ WARNING ]
app.licenseware.app_builder.app_builder:init_app:117
No reports provided

2021-08-17 08:16:57.014[ WARNING ]
app.licenseware.app_builder.app_builder:init_app:117
No reports provided

2021-08-17 08:36:02.642[ ERROR ]
app.licenseware.decorators.failsafe_decorator:wrapper:54
Traceback (most recent call last):
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/decorators/failsafe_decorator.py", line 49, in wrapper
    response = f(*args, **kwargs)
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/mongodata/mongodata.py", line 249, in fetch
    doc = list(found_docs)[0]
IndexError: list index out of range


2021-08-17 08:37:34.904[ ERROR ]
app.licenseware.decorators.failsafe_decorator:wrapper:54
Traceback (most recent call last):
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/decorators/failsafe_decorator.py", line 49, in wrapper
    response = f(*args, **kwargs)
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/mongodata/mongodata.py", line 249, in fetch
    doc = list(found_docs)[0]
IndexError: list index out of range


2021-08-17 08:38:06.698[ ERROR ]
app.licenseware.decorators.failsafe_decorator:wrapper:54
Traceback (most recent call last):
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/decorators/failsafe_decorator.py", line 49, in wrapper
    response = f(*args, **kwargs)
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/mongodata/mongodata.py", line 249, in fetch
    doc = list(found_docs)[0]
IndexError: list index out of range


2021-08-17 08:43:05.665[ ERROR ]
app.licenseware.decorators.failsafe_decorator:wrapper:54
Traceback (most recent call last):
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/decorators/failsafe_decorator.py", line 49, in wrapper
    response = f(*args, **kwargs)
  File "/home/acmt/Documents/lware/draft-lware/app/licenseware/mongodata/mongodata.py", line 249, in fetch
    doc = list(found_docs)[0]
IndexError: list index out of range


